// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okluwyniwtzptmhjyevb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbHV3eW5pd3R6cHRtaGp5ZXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzYxNTgsImV4cCI6MjA2Njc1MjE1OH0.jxl02nI6V_OseJy3XNNp1LsdSwSQOKNU5fZNgjKRnms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);